[package]
name = "et-core"
description = "Package model, layout, validation, and image IO for et"
version.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
zip = { version = "=0.6.6", default-features = false }
